feature/hw3
DoKep2/2022-2-VK-EDU-FS-Frontend-S-ELIZBARASHVILI pull request #12
Opened 2022-10-26 20:25 UTC by DoKep2

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
*
*
*

2022-10-26 20:27 UTC, martinkomitsky commented on pull_request_template.md
> +# Домашнее задание №3
Не понимаю, зачем так делать. Верни как было, плз

2022-10-26 20:27 UTC, martinkomitsky requested changes
Не вижу ДЗ в реквесте

2022-10-26 20:29 UTC, DoKep2 commented on pull_request_template.md
> +# Домашнее задание №3
Да, верну, это dummy коммит чтобы открыть пр и ишью закинуть сюда

2022-10-26 20:29 UTC, DoKep2 commented
> Не вижу ДЗ в реквесте

Я заасайню когда  можно будет смотреть)

2022-10-26 20:35 UTC, martinkomitsky commented on pull_request_template.md
> +# Домашнее задание №3
а когда задание будет?

2022-10-26 20:37 UTC, DoKep2 commented on pull_request_template.md
> +# Домашнее задание №3
Ну как пойдёт, может к 7 утра справлюсь)

2022-10-26 20:38 UTC, DoKep2 commented on pull_request_template.md
> +# Домашнее задание №3
![image](https://user-images.githubusercontent.com/86494191/198132599-98263b22-03c4-4fdb-abbc-2b6c4ab4fbfc.png)

2022-10-27 11:32 UTC, martinkomitsky commented
@DoKep2 уже все или будут еще правки?

2022-10-27 11:34 UTC, DoKep2 commented
> @DoKep2 уже все или будут еще правки?

@martinkomitsky https://github.com/DoKep2/2022-2-VK-EDU-FS-Frontend-S-ELIZBARASHVILI/pull/12#issuecomment-1292617667

2022-10-30 19:47 UTC, martinkomitsky commented
Переоткрой, пожалуйста, когда будет готово (есть кнопка reopen)

2022-10-30 19:51 UTC, DoKep2 commented
> Переоткрой, пожалуйста, когда будет готово (есть кнопка reopen)

А, я так понял чтобы не висел в списке непроверенных и не мешал?
Могу всегда сразу закрывать как только начинаю новую домашку

2022-10-30 19:53 UTC, martinkomitsky commented
Мы проверяем дату сдачи ДЗ от даты создания PR. Лучше открывать PR тогда, когда решение готово к проверке

2022-10-30 19:54 UTC, DoKep2 commented
Грустно

2022-10-31 00:20 UTC, DoKep2 commented
Я когда-нибудь обязательно зарезолвлю все тудушки и разнесу код по файликам, но не сейчас.......

![image](https://user-images.githubusercontent.com/86494191/198909161-285cc567-e8a9-4bab-bb2a-891e4a3993ec.png)

2022-11-01 07:13 UTC, martinkomitsky approved these changes
ну, раз тут такое дело, то и проверять-то особо нечего. 
Учитывая еще и просрочку, могу поставить только 7...

2022-11-01 07:13 UTC, merged